config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  get 'home/about'
  #root 'home#index'
  root 'friends#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
    @name_r = "Raj Kumar"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
    <br/>
  </div>

  <div class="field form-group">
  
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
    <br/>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
    <br/>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
    <br/>
  </div>

  <div class="field form-group">
    
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twiter" %>
    <br/>
  </div>
  <div class="field form-group">
    
    <%= form.number_field :user_id, id: :friend_user, class:"form-control", value:current_user.id, type: :hidden %>
    <br/>
  </div>
  

  <div class="field form-group">
    <%= form.submit %>
    <br/>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class:"btn btn-success"%> |
  <%= link_to "Back to friends", friends_path,class:"btn btn-success" %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>

<% if user_signed_in? %>
<table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Twitter</th>
        <th>colspan="3"</th>
      </tr>
    </thead>

    <tbody>
      <% @friends.each do |friend| %>
    <%= render friend %>
    <p>
      <%= link_to "Show this friend", friend, class:"btn btn-secondary"%>
    </p>
  <% end %>
    </tbody>
  </table>
  <%= link_to 'New Friend', new_friend_path, class:"btn btn-secondary" %>
  <% else %>
    <h1>Hello World!2</h1>
  <% end %>

   

app/views/friends/new.html.erb
<h1> Add New Friend</h1>


<%= render "form", friend: @friend %>

<br/>

<div>
  <%= link_to "Back to friends", friends_path,class:"btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4"><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p class="lead"><%= @friend.email %> | <%= @friend.phone %> | <%= @friend.twitter %> 
  </p>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class:"btn btn-dark" %> |
  <%= link_to "Back to friends", friends_path, class:"btn btn-dark" %>
  <br/><br/>

  <%= button_to "Destroy this friend",  @friend, method: :delete %>
  <hr class="my-4">
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Friend App', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "About Us",home_about_path,class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Friends",friends_path,class:"nav-link"%>
      </li>
      
      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Add Friend",new_friend_path,class:"nav-link"%>
       </li>
        <li class="nav-item">
        <%= link_to "Sign Out",destroy_user_session_path,method: :delete, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit Profile",edit_user_registration_path,class:"nav-link"%>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up",new_user_registration_path,class:"nav-link"%>
      </li>
      <li class="nav-item">
        <%= link_to "Sign In",new_user_session_path,class:"nav-link"%>
      </li>
      <% end %>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>We are in about</h1>

<p>
	<%= @name_r %>
</p>

app/views/home/index.html.erb
<h1>Hello World!2</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Friends App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
    <%= render 'home/header' %>
  </div>
    <div class="container">
      <br/>
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>